### ISSUE TITLE
关于trajectory.txt的轨迹

### ISSUE THREAD

**Issue by wuyukun-tong** [HybridRobotics/prompt2walk#1]
您好，我看到trajectory.txt是一个19维向量组成的序列，我看run.py代码里面的定义后面12维是关节位置，前面7维应该是rpy和四元素，我想确认一个前面其为的具体含义，谢谢！

**Comment by wangyenjen** [comment]
@wuyukun-tong 你好，

这19维向量分别对应着机器人本体位置（3维）、本体方向（4维），及关节位置（12维）。

**Comment by wuyukun-tong** [comment]
感谢回复！另外想问一下你们训练数据的规模是多少！

**Comment by wangyenjen** [comment]
Hi @wuyukun-tong,

不好意思现在才给予回覆，我们的强化学习是在isaac中训练1500个episode，而prompt2walk的部分，具体可以参考论文中history observations的长度。
