### ISSUE TITLE
关于采样频率

### ISSUE THREAD

**Issue by wuyukun-tong** [HybridRobotics/prompt2walk#2]
您好，想问一下训练数据的采样频率是多少呀，一般狗的控制频率是1000hz，采集到这个数据之后直接去训模型还是需要进行滤波之后再去训练模型！谢谢！

**Comment by wangyenjen** [comment]
@wuyukun-tong 你好，

我们的控制是基于PD控制的，底层PD确实是500 ~ 1000，甚至2000 Hz，而上层的policy输出是10 Hz，具体内容可以参考我们的论文。
